version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    depends_on:
      - chrome  # Ensure 'chrome' service is started before 'web'

  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - "4444:4444"  # Expose Selenium server port

networks:
  default:
    name: zospital_default
